### ISSUE TITLE
Debug build in 'dist'

### ISSUE THREAD

**Issue by Fequois** [SubZane/simplegmaps#11]
I believe the scripts in the 'dist' directory are improperly built from a development/debug source as they contain several `console.log` statements (whereas the actual source file has none).

Not sure if this is intentional or not, but thought I'd flag it nevertheless.

(Off-topic: I love this plugin. It does exactly what I need and it's small!)

**Comment by SubZane** [comment]
I'll look in to it :)

**Comment by SubZane** [comment]
Fixed in 0.7.1
