### ISSUE TITLE
"Retina" map marker

### ISSUE THREAD

**Issue by Fequois** [SubZane/simplegmaps#12]
Hey,

Just wondering whether it's possible to add a feature to load a HiDPI asset for the map markers. Say, a parameter along the lines of `retina = true` to make it look for an @2x asset if pixel density is above X, with a fallback if not found.

I found an example implementation here: http://www.minijus.lt/blog/uncategorized/how-to-add-retina-ready-pin-marker-to-your-google-maps/

Thanks!

**Comment by SubZane** [comment]
Sounds like a good feature :)

**Comment by Fequois** [comment]
Yay! I would make a PR if I could. :smile:

**Comment by SubZane** [comment]
This should now be fixed in 0.9.0. Check out the demo for example :)

**Comment by Fequois** [comment]
Nice! Thanks a lot. :smiley:
