### ISSUE TITLE
warning: watchPosition() and getPosition() are deprecated

### ISSUE THREAD

**Issue by mikegrungey** [SubZane/simplegmaps#14]
Hi, I got this warning when uploaded to the web? is it due to non-secure site? hope you can help me out. 

"getCurrentPosition() and watchPosition() are deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details"

**Comment by SubZane** [comment]
I will check it out.

**Comment by SubZane** [comment]
Can you provide me with an URL with an example so I can see for myself?

**Comment by mikegrungey** [comment]
http://amricreative.com/olivehouse_web/agents_map.php

**Comment by SubZane** [comment]
Thanks. I can now reproduce the same warnings on my dev. I'll get to fix it!

**Comment by mikegrungey** [comment]
thanks.

**Comment by SubZane** [comment]
Following up. It seems that Google plans to disable geolocation on non-secure locations. Meaning that it will require HTTPS in order for geolocation to work.

https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

**Comment by SubZane** [comment]
After even further research I learned that this has nothing to do with google maps or my script. It is all about Google Chrome. Therefore not a bug.
