### ISSUE TITLE
How to trigger map resize?

### ISSUE THREAD

**Issue by breadadams** [SubZane/simplegmaps#16]
Hey, I'm using a hide/show toggle button to increase the height of the map, but theres a grey section - the height of the difference in size (until the window gets resized).

I've tried using regular google maps triggers, but doesn't seem to be working. Is there anything in *simplegmaps* for this? :smiley: 

Here's what I'm doing...

    $('.mapToggle').click( function(e) {

        e.preventDefault();
		
        var map = $('#postMap');
		
        google.maps.event.trigger(map, 'resize');
    
    ...

**Comment by SubZane** [comment]
Hmm I'm not sure the current version supports this. I think I need to add a public method to tell googlemaps to resize.

**Comment by SubZane** [comment]
Solved by @slackero
