### ISSUE TITLE
SnazzyMaps/scrollwheel issue

### ISSUE THREAD

**Issue by breadadams** [SubZane/simplegmaps#17]
Hey! Just noticed, it seems simplegmaps is ignoring the `scrollwheel: false,` argument if there are `MapOptions: { styles...`. It's happening on the *snazzy colors* example on the simplegmaps page.

You see what I mean?

Cheers!

**Comment by breadadams** [comment]
Rookie mistake... I was adding `scrollwheel` settings after I'd closed `MapOptions:` :dizzy_face:

**Comment by SubZane** [comment]
cool :)
