### ISSUE TITLE
Multiple markers with custom icon

### ISSUE THREAD

**Issue by CesarRotela** [SubZane/simplegmaps#18]
Multiple markers with custom icon with long/lat...........fails

Multiple markers with custom icon with data-address...........fails

It is a bug?

**Comment by SubZane** [comment]
possibly, yes

**Comment by CesarRotela** [comment]
Thank you very much for your quick response, and thank you for this excellent plugin,
( sorry for my English is not my official language)

http://cesarrotela.com/cliente/simplegmaps/simplegmaps.html

As you can see, I can only show an icon, and have two different icons with different long/lat

What am I doing wrong?

**Comment by SubZane** [comment]
Confirmed.
There is a bug when using custom icons and long/lat

**Comment by SubZane** [comment]
This issue has been resolved with version [1.1.3](https://github.com/SubZane/simplegmaps/tree/1.1.3)
