### ISSUE TITLE
Multiple maps on same page

### ISSUE THREAD

**Issue by breadadams** [SubZane/simplegmaps#19]
I'm trying to show multiple maps on the same page, they all have the exact same markup, however only the first map displays.

Does *simplegmaps* not support this? Or is it down to the markup?

Cheers!

**Comment by breadadams** [comment]
Was targeting an ID in js... changing to a class fixed, _goddammitfronk_

**Comment by xstortionist** [comment]
@breadadams how did you achieve this? I'm using a class and it only displays one map.

**Comment by breadadams** [comment]
@xstortionist Don't think I did anything special, just setup multiple maps with identical markup (except markers, those were different on each map). And then:

```
simplegmaps.init({
  container: '.containerClass'
});
```

*I think*, it's really bugging me 'cause I can't recall what project I used this on, else I'd check for you...

**Comment by xstortionist** [comment]
@breadadams yea, for whatever reason I can't get it to work. I'm doing exactly the same thing but it only initializes the first map for me. Let me know if you find the project, i'd like to see what you did because I can't get it work to save my life and I don't have time to shift through google api docs right now.

**Comment by breadadams** [comment]
Found it, this is the exact js I used:

```
$('.map-canvas').simplegmaps({
	  MapOptions: {
  		// Options Here
  	}
  });
```

**Comment by xstortionist** [comment]
yea, that doesn't seem to work anymore since he moved project over to vanilla :/ I appreciate the help.

**Comment by breadadams** [comment]
Aha, no problem. Just checked and I was using v1.0.2 on the mentioned project.

On a sidenote, and in no way bad-mouthing simplegmaps (as it's great to get a quick map working). After an afternoon learning up on the Google Maps API, I find it much easier to get a custom map running (multiple on page, multiple pins, clustering, etc.) with this rather than map plugins.

**Comment by xstortionist** [comment]
@breadadams I'm about to go that route myself here in a bit but I feel like I just wasted a few hours getting this setup in the project.
