### ISSUE TITLE
Multiple Info windows

### ISSUE THREAD

**Issue by webchun** [SubZane/simplegmaps#22]
Hi, thanks for such a nice plugin!
Anyway I have an issue with multiple markers. When we have multiple markers, clicking on any  markers will not close the other one, so if we not clicking on the close button, all info windows will open. Is there any built in solution so only one infowindow open at a time? 

Here's the screenshot :

![ss](http://i.imgur.com/SCinJkY.jpg?1)

**Comment by SubZane** [comment]
Sounds like a reasonable feature request! :)

**Comment by SubZane** [comment]
Fixed in version 2.2.0
