### ISSUE TITLE
On click move to marker?

### ISSUE THREAD

**Issue by xstortionist** [SubZane/simplegmaps#23]
Is it possible on click of element outside of the map to move to a specific marker within the map?

Also, I notice on intial page load, .map-infowindow is visible, I simply fix this by adding class onload as follows

`$('.map-infowindow').addClass('visible');`

**Comment by SubZane** [comment]
1. No, but it can be done using the eventhandling available. google maps has click events that you can hook.

2. Is it? where? Checking my demo I cannot see it's visible until I click?

**Comment by xstortionist** [comment]
@SubZane thanks, I'm going to take a look at the api click events you speak of here shortly.

2. That's the odd thing, it's not doing it on your demo but I believe it may be because you can't load info window without clicking through the hud on your demo page. Perhaps, it displays this way on my end because I'm initializing with jquery? I'll be honest, I haven't had much time to swing back around and play with the maps but I'll be working with it exclusively this week.

It's a wonderful plugin, so I thank you for your time spent on this great product. I'll keep you posted.

**Comment by xstortionist** [comment]
@SubZane I figured out why info window is visible on load, it's because I was using v1.1.3 - this works as expected on v2.0.0 beta. Sorry for the confusion.

**Comment by SubZane** [comment]
no problem! :)
