### ISSUE TITLE
TypeError: el is null on all pages except the one with the map

### ISSUE THREAD

**Issue by trizonia** [SubZane/simplegmaps#26]
Hi there!
I'm using the library on three WordPress installations. On one it works fine but on the other two I get the following error on all pages except the one with the map:
TypeError: el is null http://..../simplegmaps.js?ver=4.7 Line 736
Looking at the code, this line is here:
`if (el.hasAttribute('data-json')) {
settings.jsonsource = el.getAttribute('data-json');
}`
The map displays without problems, but it would be great not to get the error.
Also, I don't know whether it is related to the issue, but the code with the issue is the Vanilla JS version.

Thank you very much

**Comment by SubZane** [comment]
Seems to me like you are initializing the script even if there is no map to render? That's why there's a null exception.

**Comment by trizonia** [comment]
Thank you for taking the time to respond. Yes, I guess that's the problem - my JS knowledge is extremely basic, as you can tell. So, it isn't possible to use the script on a website where it's always loaded (even when there is no map)?

**Comment by SubZane** [comment]
Do a javascript-check to see if there is a DIV element for simplegmaps or not, and if it exists, init simplegmaps, otherwise, don't

**Comment by trizonia** [comment]
Yes, this worked! Thank you very, very much for your help!!!!
